---
eck-elasticsearch:
  fullnameOverride: "telemetry-es"
  version: 8.9.0
  nodeSets:
    - name: masters
      count: 1
      config:
        # node.roles: ["master", "data"]
        node.store.allow_mmap: false
      podTemplate:
        spec:
          containers:
            - name: elasticsearch
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 1Ti
            storageClassName: managed #TODO: managed-premium
  http:
    tls:
      selfSignedCertificate:
        disabled: false
