eck-elasticsearch:
  annotations:
    eck.k8s.elastic.co/license: basic
  version: 8.9.0
  nodeSets:
    - name: node
      count: 1
      config:
        node.store.allow_mmap: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 128Gi
            storageClassName: managed
  http:
    tls:
      selfSignedCertificate:
        disabled: false
