---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: flux-config
spec:
  targetNamespace: omni
  releaseName: operator-release
  interval: 1m
  chart:
    spec:
      chart: eck-operator
      version: "2.9.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
  valuesFrom:
    - kind: ConfigMap
      name: operator-values
      valuesKey: operator-values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-stack
  namespace: flux-config
spec:
  dependsOn:
    - name: elastic-operator
  targetNamespace: omni
  releaseName: esk-release
  interval: 1m
  chart:
    spec:
      chart: eck-stack
      version: "0.7.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
  valuesFrom:
    - kind: ConfigMap
      name: elastic-values
      valuesKey: elastic-values.yaml
    - kind: ConfigMap
      name: kibana-values
      valuesKey: kibana-values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: apm-server
  namespace: flux-config
spec:
  dependsOn:
    - name: elastic-stack
  targetNamespace: omni
  releaseName: apm-release
  interval: 1m
  chart:
    spec:
      chart: apm-server
      version: "8.5.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
  valuesFrom:
    - kind: ConfigMap
      name: apm-values
      valuesKey: apm-values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otlp-collector
  namespace: flux-config
spec:
  dependsOn:
    - name: apm-server
  targetNamespace: omni
  releaseName: otlp-release
  interval: 1m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.72.0"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
  valuesFrom:
    - kind: ConfigMap
      name: otlp-values
      valuesKey: otlp-values.yaml
