---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-operator
  namespace: flux-config
spec:
  targetNamespace: mynamespace
  releaseName: elastic-operator
  interval: 5m
  chart:
    spec:
      chart: eck-operator
      version: "2.9.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
  valuesFrom:
    - kind: ConfigMap
      name: operator-values
      valuesKey: operator-values.yaml
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic-stack
  namespace: flux-config
spec:
  dependsOn:
    - name: elastic-operator
  targetNamespace: mynamespace
  releaseName: es-quickstart
  interval: 5m
  chart:
    spec:
      chart: eck-stack
      version: "0.7.0"
      sourceRef:
        kind: HelmRepository
        name: elastic
  valuesFrom:
    - kind: ConfigMap
      name: elastic-values
      valuesKey: elastic-values.yaml
    - kind: ConfigMap
      name: kibana-values
      valuesKey: kibana-values.yaml
