apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-config
spec:
  targetNamespace: mynamespace
  releaseName: elastic-operator
  interval: 1h
  chart:
    spec:
      chart: elastic/eck-operator
      version: "2.9.0"
      sourceRef:
        kind: HelmRepository
        name: elastic-operator
  valuesFrom:
    - kind: ConfigMap
      name: elastic-operator-values
      valuesKey: myvalues.yaml
