apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-config
spec:
  #targetNamespace: omni
  releaseName: ingress-nginx
  interval: 1h
  chart:
    spec:
      chart: ingress-nginx
      version: "4.7.1"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  valuesFrom:
    - kind: ConfigMap
      name: ingress-nginx-values
      valuesKey: myvalues.yaml
