eck-kibana:
  annotations:
    eck.k8s.elastic.co/license: basic
  version: 8.9.0
  spec:
    count: 1
    elasticsearchRef:
      name: es-quickstart-eck-elasticsearch
      # namespace: default
    http:
      #service:
      #  spec:
      #    # Type of service to deploy for Kibana.
      #    # This deploys a load balancer in a cloud service provider, where supported.
      #    #
      #    type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
