---
eck-kibana:
  fullnameOverride: telemetry
  spec:
    count: 1
    elasticsearchRef:
      name: telemetry-es
    http:
      tls:
        selfSignedCertificate:
          disabled: true
    config:
      xpack.fleet.packages:
        - name: apm
          version: latest
      xpack.fleet.agentPolicies:
        - name: otlp
          namespace: omni
          package_policies:
            - name: APM Policy
              namespace: omni
              package:
                name: apm
              inputs:
              - type: apm
                enabled: true
                vars:
                  - name: host
                    value: telemetry-apm:8200
                  - name: url
                    value: http://telemetry-apm:8200
