---
eck-kibana:
  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      #service:
      #  spec:
      #    type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
    config:
      xpack.fleet.packages:
        - name: apm
          version: latest
      xpack.fleet.agentPolicies:
        - name: otlp
          namespace: mynamespace
          package_policies:
            - name: APM Policy
              namespace: mynamespace
              package:
                name: apm
                inputs:
                - type: apm
                  enabled: true
                  vars:
                    - name: host
                      value: "apm-release-apm-server:8200"
                    - name: url
                      value: "http://apm-release-apm-server:8200"
