---
eck-kibana:
  spec:
    count: 1
    elasticsearchRef:
      name: elasticsearch
    http:
      #service:
      #  spec:
      #    type: LoadBalancer
      tls:
        selfSignedCertificate:
          disabled: true
