apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - namespace.yaml
configMapGenerator:
  - name: ingress-nginx-values
    namespace: flux-config
    files:
      - myvalues.yaml=myvalues.yaml
    options:
      disableNameSuffixHash: true
