apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - namespace.yaml
  - secret.yaml
configMapGenerator:
  - name: operator-values
    namespace: flux-config
    files:
      - operator-values.yaml=operator-values.yaml
    options:
      disableNameSuffixHash: true
  - name: elastic-values
    namespace: flux-config
    files:
      - elastic-values.yaml=elastic-values.yaml
    options:
      disableNameSuffixHash: true
  - name: kibana-values
    namespace: flux-config
    files:
      - kibana-values.yaml=kibana-values.yaml
    options:
      disableNameSuffixHash: true
  - name: apm-values
    namespace: flux-config
    files:
      - apm-values.yaml=apm-values.yaml
    options:
      disableNameSuffixHash: true
  - name: otlp-values
    namespace: flux-config
    files:
      - otlp-values.yaml=otlp-values.yaml
    options:
      disableNameSuffixHash: true
