apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - helmrepository.yaml
  - namespace.yaml
configMapGenerator:
  - name: operator-values
    namespace: mynamespace
    files:
      - operator-values.yaml=operator-values.yaml
    options:
      disableNameSuffixHash: true
  - name: elastic-values
    namespace: mynamespace
    files:
      - elastic-values.yaml=elastic-values.yaml
    options:
      disableNameSuffixHash: true
  - name: kibana-values
    namespace: mynamespace
    files:
      - kibana-values.yaml=kibana-values.yaml
    options:
      disableNameSuffixHash: true
