apiVersion: apps/v1
kind: Deployment
metadata:
  name: open-telemetry-exemple-deployment
  namespace: mynamespace
  labels:
    app: open-telemetry-exemple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-telemetry-exemple
  template:
    metadata:
      labels:
        app: open-telemetry-exemple
    spec:
      containers:
        - name: open-telemetry-exemple
          image: olhitestacr1.azurecr.io/open-telemetry-exemple:1.0
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: open-telemetry-exemple-settings
  namespace: mynamespace
data:
  appsettings.json: |-
    {
      "Logging": {
        "LogLevel": {
          "Default": "Warning",
          "System": "Warning",
          "Microsoft": "Warning"
        }
      },
      "Otlp": {
        "Endpoint": "http://otlp-release-opentelemetry-collector:4317",
        "Protocol": "Grpc",
        "ExportProcessorType": "Batch"
      }
    }
