mode: deployment
fullnameOverride: otelcollector
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
  health:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    protocol: TCP
config:
  extensions:
    basicauth/server:
      htpasswd:
        inline: |
          omfo247:f1hN)P*~nK~5GX6
    health_check:
      endpoint: ${env:MY_POD_IP}:13133
  receivers:
    otlp:
      protocols:
        http:
          cors:
            allowed_origins: ["*"]
            allowed_headers: ["*"]
          auth:
            authenticator: basicauth/server
        grpc:
          endpoint: ${env:MY_POD_IP}:4317
  exporters:
    otlp/es:
      endpoint: telemetry-apm:8200
      tls:
        insecure: true
    logging:
      verbosity: detailed
  service:
    extensions: [basicauth/server, health_check]
    pipelines:
      traces:
        receivers:
          - otlp
        exporters:
          - logging
          - otlp/es
      metrics:
        receivers:
          - otlp
        exporters:
          - logging
          - otlp/es
      logs:
        receivers:
          - otlp
        exporters:
          - logging
          - otlp/es
