mode: "deployment"
ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
    appProtocol: grpc
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP
  health:
    enabled: true
    containerPort: 13133
    servicePort: 13133
    protocol: TCP
config:
  extensions:
    basicauth/server:
      htpasswd:
        inline: |
          omfo247:f1hN)P*~nK~5GX6
    health_check:
      endpoint: 0.0.0.0:13133
  receivers:
    otlp:
      protocols:
        http:
          cors:
            allowed_origins: ["*"]
            allowed_headers: ["*"]
          auth:
            authenticator: basicauth/server
        grpc:
  exporters:
    otlp/es:
      endpoint: apm-release-apm-server:8200
      tls:
        insecure: false
        insecure_skip_verify: true
      # tls:
      #   insecure_skip_verify: true
    logging:
      loglevel: debug
  service:
    extensions: [basicauth/server, health_check]
    pipelines:
      traces:
        receivers:
          - otlp
        exporters:
          - logging
          - otlp/es
      metrics:
        receivers:
          - otlp
        exporters:
          - logging
          - otlp/es
      logs:
        receivers:
          - otlp
        exporters:
          - logging
          - otlp/es
